version: '3.8'
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '3001:3001'
    volumes:
      - ./server:/backend
      - /backend/node_modules

  client:
    build: ./client
    container_name: client_c
    volumes:
      - "./client:/frontend:delegated"
      - /frontend/node_modules/
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - server
   
    